export const REQUEST_AUTH = "REQUEST_AUTH";
export const REQUEST_AUTH_FINISHED = "REQUEST_AUTH_FINISHED";

export const REQUEST_DEAUTH = "REQUEST_DEAUTH";
export const REQUEST_DEAUTH_FINISHED = "REQUEST_DEAUTH_FINISHED";
