export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR';
export const DEAUTHENTICATE = 'DEAUTHENTICATE';
export const DEAUTHENTICATE_ERROR = 'DEAUTHENTICATE_ERROR';
