export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR';
export const DEAUTHENTICATE = 'DEAUTHENTICATE';
export const DEAUTHENTICATE_ERROR = 'DEAUTHENTICATE_ERROR';
export const CLIENT_AUTHENTICATE = 'CLIENT_AUTHENTICATE';
export const CLIENT_AUTHENTICATE_ERROR = 'CLIENT_AUTHENTICATE_ERROR';
export const CLIENT_DEAUTHENTICATE = 'CLIENT_DEAUTHENTICATE';
