export const FETCH_SURVEYS = 'FETCH_SURVEYS';
export const FETCH_SURVEYS_ERROR = 'FETCH_SURVEYS_ERROR';
export const FETCH_SURVEY = 'FETCH_SURVEY';
export const FETCH_SURVEY_ERROR = 'FETCH_SURVEY_ERROR';
